[build]
  functions = "netlify/functions"

[[redirects]]
  from   = "/api/create-preference"
  to     = "/.netlify/functions/create-preference"
  status = 200

[[redirects]]
  from   = "/api/webhook"
  to     = "/.netlify/functions/webhook"
  status = 200
